version: '3.3'

services:
  db:
    image: mysql:8.0
    container_name: hll_docupet_db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: hll_docupet
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
